# Generated by Django 3.2.6 on 2021-08-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generaluser',
            options={},
        ),
        migrations.AddField(
            model_name='generaluser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='generaluser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
