# Generated by Django 3.2.6 on 2021-08-05 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='photo5',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.ImageField(blank=True, null=True, upload_to='Post/%y/%m/%d')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.post')),
            ],
        ),
    ]
