# Generated by Django 3.2.6 on 2021-08-06 07:50

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A hashtag-separated list of tags.', through='community.TaggedPost', to='taggit.Tag', verbose_name='tags'),
        ),
    ]
