# Generated by Django 3.2.6 on 2021-09-27 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='조회날짜')),
                ('client_ip', models.GenericIPAddressField(null=True, verbose_name='사용자 Ip주소')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.cardnews', verbose_name='조회한 게시물')),
            ],
        ),
    ]
