# Generated by Django 3.2.6 on 2021-08-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(default='base/baseimg.png', upload_to='plant')),
                ('water_period', models.PositiveIntegerField(blank=True, null=True)),
                ('growth_velocity', models.PositiveIntegerField(blank=True, null=True)),
                ('growth_type', models.TextField(blank=True)),
                ('sunlight', models.PositiveIntegerField(blank=True, null=True)),
                ('growth_temp', models.PositiveIntegerField(blank=True, null=True)),
                ('care_difficulty', models.PositiveIntegerField(blank=True, null=True)),
                ('humidity', models.PositiveIntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
