# Generated by Django 3.2.6 on 2021-08-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='growth_type',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='growth_velocity',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='water_period',
        ),
        migrations.AddField(
            model_name='plant',
            name='flower',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='plant',
            name='growth_form',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='plant',
            name='management_level',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='plant',
            name='photo_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='water_period_autumn',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='plant',
            name='water_period_spring',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='plant',
            name='water_period_summer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='plant',
            name='water_period_winter',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='plant',
            name='care_difficulty',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='plant',
            name='growth_temp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='humidity',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='sunlight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
